"""Utilities for Parallel Finder.

This package exposes shared constants and helper functions used by the core
analysis stack and the PySide6 UI.
"""

from __future__ import annotations

from .constants import (
    APP_NAME,
    APP_ROOT,
    APP_VERSION,
    AUTOSAVE_INTERVAL,
    BASE_DIR,
    BATCH_SIZE_DEFAULT,
    CACHE_DIR,
    CONFIG_DIR,
    DEFAULT_FPS,
    DUPLICATE_WINDOW,
    EXPORT_DIR,
    FLIP_INDICES,
    HEAD_TURN_THRESHOLD,
    KEYPOINT_CONF_THRESHOLD,
    LOG_DIR,
    MODELS_DIR,
    NUM_KEYPOINTS,
    POSE_CACHE_DIR,
    POSE_KEYPOINTS,
    PREVIEW_CACHE_DIR,
    PREVIEW_SIZE,
    PROJECTS_DIR,
    SKELETON_CONNECTIONS,
    THEMES,
    USER_DATA_DIR,
    VIDEO_EXTENSIONS,
    YOLO_CONF,
    YOLO_IMGSZ,
)
from .helpers import (
    ArrayF32,
    Direction,
    compact_number,
    direction_to_emoji,
    direction_to_string,
    format_time,
    get_file_hash,
    normalize_pose,
    numpy_to_qpixmap,
    to_timecode,
)

__all__ = [
    "APP_NAME",
    "APP_ROOT",
    "APP_VERSION",
    "AUTOSAVE_INTERVAL",
    "BASE_DIR",
    "BATCH_SIZE_DEFAULT",
    "CACHE_DIR",
    "CONFIG_DIR",
    "DEFAULT_FPS",
    "DUPLICATE_WINDOW",
    "EXPORT_DIR",
    "FLIP_INDICES",
    "HEAD_TURN_THRESHOLD",
    "KEYPOINT_CONF_THRESHOLD",
    "LOG_DIR",
    "MODELS_DIR",
    "NUM_KEYPOINTS",
    "POSE_CACHE_DIR",
    "POSE_KEYPOINTS",
    "PREVIEW_CACHE_DIR",
    "PREVIEW_SIZE",
    "PROJECTS_DIR",
    "SKELETON_CONNECTIONS",
    "THEMES",
    "USER_DATA_DIR",
    "VIDEO_EXTENSIONS",
    "YOLO_CONF",
    "YOLO_IMGSZ",
    "ArrayF32",
    "Direction",
    "compact_number",
    "direction_to_emoji",
    "direction_to_string",
    "format_time",
    "get_file_hash",
    "normalize_pose",
    "numpy_to_qpixmap",
    "to_timecode",
]

__version__ = APP_VERSION
